#!/usr/bin/env bash
# Fixing web server to run nginx as user

# setting user in config by replacing user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replacing port 80 with 8080 in sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# giving owner permissions r+w to config file
chmod 644 /etc/nginx/nginx.conf

# killing apache process if running
pkill apache2

# starting nginx service using new user
sudo -u nginx service nginx start
